name: example.configuring.exec.workstations
topology:
  nodes:
    workstation1:
      kind: linux
      image: alpine:latest
      labels:
        graph-icon: host
        graph-layer: 1
      exec:
        - apk update
        - apk add iproute2 bash
        - ip addr add 10.0.0.1/24 dev eth1
        - ip link set eth1 up

    workstation2:
      kind: linux
      image: alpine:latest
      labels:
        graph-icon: host
        graph-layer: 2
      exec:
        - apk update
        - apk add iproute2 bash
        - ip addr add 10.0.0.2/24 dev eth1
        - ip link set eth1 up

  links: 
    - endpoints: ['workstation1:eth1', "workstation2:eth1"]